import type { Product, Project } from "./types";

export const projects: Project[] = [
  {
    id: "aurora-fashion",
    title: "Aurora Fashion Film",
    role: "Edit, Grade, Sound Design",
    category: "cinematic",
    year: "2026",
    posterUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1400&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    featured: true,
  },
  {
    id: "metro-pulse",
    title: "Metro Pulse",
    role: "Motion-led music edit",
    category: "motion-graphics",
    year: "2025",
    posterUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "ember-wedding",
    title: "Ember Wedding Story",
    role: "Cinematic Wedding Film",
    category: "cinematic",
    year: "2025",
    posterUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "craft-notes",
    title: "Craft Notes",
    role: "Documentary Assembly",
    category: "documentary-style",
    year: "2024",
    posterUrl: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1400&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "launch-shorts",
    title: "Launch Shorts System",
    role: "UGC launch ad package",
    category: "ugc-ad",
    year: "2026",
    posterUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    format: "portrait",
  },
  {
    id: "neural-product-film",
    title: "Neural Product Film",
    role: "AI-assisted brand video",
    category: "ai-videos",
    year: "2026",
    posterUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "creator-testimonial-cut",
    title: "Creator Testimonial Cut",
    role: "Vertical UGC testimonial",
    category: "ugc-ad",
    year: "2026",
    posterUrl: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?auto=format&fit=crop&w=900&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    format: "portrait",
  },
  {
    id: "ai-fashion-reel",
    title: "AI Fashion Reel",
    role: "Portrait AI social video",
    category: "ai-videos",
    year: "2026",
    posterUrl: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=900&q=80",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    format: "portrait",
  },
];

export const products: Product[] = [
  {
    id: "cinematic-lut-pack-01",
    title: "Cinematic LUT Pack 01",
    category: "LUTs",
    price: 49,
    coverUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    description: "A clean, premium color base for commercials, weddings, music videos, and social launch films.",
    features: ["18 production LUTs", "Rec.709 and Log variants", "Resolve, Premiere, Final Cut support", "Instant digital delivery"],
  },
  {
    id: "title-motion-toolkit",
    title: "Title Motion Toolkit",
    category: "Premium Text Animations",
    price: 59,
    coverUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
    description: "Deluxe motion typography packs for titles, lower thirds, and editorial callouts.",
    features: ["30 animated text templates", "Modular blur and glow styles", "After Effects friendly", "Quick export-ready render presets"],
    fileUrl: "https://example.com/premium-title-motion-toolkit.zip",
  },
  {
    id: "free-motion-graphics-pack",
    title: "Free Motion Graphics Pack",
    category: "Free Motion Graphics",
    price: 0,
    coverUrl: "https://images.unsplash.com/photo-1523473827532-cc7d17f3633a?auto=format&fit=crop&w=1200&q=80",
    description: "A free starter kit of motion backgrounds, transitions, and animated elements for editors.",
    features: ["35 motion assets", "Transparent PNG and MP4 overlays", "Social format-ready", "No attribution required"],
    fileUrl: "https://example.com/free-motion-graphics-pack.zip",
    isFree: true,
  },
  {
    id: "editor-essentials-bundle",
    title: "Editor Essentials Bundle",
    category: "Editor Essentials",
    price: 29,
    coverUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    description: "Templates, workflow guides, and finishing assets built for fast editorial polish.",
    features: ["In-out marker kits", "Timeline organization templates", "Render presets", "Bonus quick-start guide"],
  },
  {
    id: "grain-soundscapes",
    title: "Grain Soundscapes",
    category: "Editor Essentials",
    price: 39,
    coverUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80",
    description: "Minimal cinematic textures, risers, room tones, and soft impact layers for polished post-production.",
    features: ["120 WAV assets", "24-bit masters", "Organized by mood", "Royalty-free"],
  },
];
